package keys

import "testing"

var result []string

func BenchmarkIndex(b *testing.B) {
	for i := 0; i < b.N; i++ {
		keys := make([]string, len(data))
		j := 0
		for k := range data {
			keys[j] = k
			j++
		}
	}
}

func BenchmarkAppend(b *testing.B) {
	for i := 0; i < b.N; i++ {
		keys := make([]string, 0, len(data))
		for k := range data {
			keys = append(keys, k)
		}
	}
}

// A bunch of data for our test. Map of cities in Alaska to their county name.
var data = map[string]string{
	"ADAK":                 "ALEUTIANS WEST",
	"AKIACHAK":             "BETHEL",
	"AKIAK":                "BETHEL",
	"AKUTAN":               "ALEUTIANS EAST",
	"ALAKANUK":             "WADE HAMPTON",
	"ALEKNAGIK":            "DILLINGHAM",
	"ALLAKAKET":            "YUKON KOYUKUK",
	"AMBLER":               "NORTHWEST ARCTIC",
	"ANAKTUVUK PASS":       "NORTH SLOPE",
	"ANCHOR POINT":         "KENAI PENINSULA",
	"ANCHORAGE":            "ANCHORAGE",
	"ANDERSON":             "DENALI",
	"ANGOON":               "HOONAH ANGOON",
	"ANIAK":                "BETHEL",
	"ANVIK":                "YUKON KOYUKUK",
	"ARCTIC VILLAGE":       "YUKON KOYUKUK",
	"ATKA":                 "ALEUTIANS WEST",
	"ATQASUK":              "NORTH SLOPE",
	"AUKE BAY":             "JUNEAU",
	"BARROW":               "NORTH SLOPE",
	"BEAVER":               "YUKON KOYUKUK",
	"BETHEL":               "BETHEL",
	"BETTLES FIELD":        "YUKON KOYUKUK",
	"BIG LAKE":             "MATANUSKA SUSITNA",
	"BREVIG MISSION":       "NOME",
	"BUCKLAND":             "NORTHWEST ARCTIC",
	"CANTWELL":             "DENALI",
	"CENTRAL":              "YUKON KOYUKUK",
	"CHALKYITSIK":          "YUKON KOYUKUK",
	"CHEFORNAK":            "BETHEL",
	"CHEVAK":               "WADE HAMPTON",
	"CHICKEN":              "SOUTHEAST FAIRBANKS",
	"CHIGNIK":              "LAKE AND PENINSULA",
	"CHIGNIK LAGOON":       "LAKE AND PENINSULA",
	"CHIGNIK LAKE":         "LAKE AND PENINSULA",
	"CHITINA":              "VALDEZ CORDOVA",
	"CHUGIAK":              "ANCHORAGE",
	"CIRCLE":               "YUKON KOYUKUK",
	"CLAM GULCH":           "KENAI PENINSULA",
	"CLARKS POINT":         "DILLINGHAM",
	"CLEAR":                "DENALI",
	"COFFMAN COVE":         "PRINCE OF WALES HYDER",
	"COLD BAY":             "ALEUTIANS EAST",
	"COOPER LANDING":       "KENAI PENINSULA",
	"COPPER CENTER":        "VALDEZ CORDOVA",
	"CORDOVA":              "VALDEZ CORDOVA",
	"CRAIG":                "PRINCE OF WALES HYDER",
	"CROOKED CREEK":        "BETHEL",
	"DEERING":              "NORTHWEST ARCTIC",
	"DELTA JUNCTION":       "SOUTHEAST FAIRBANKS",
	"DENALI NATIONAL PARK": "DENALI",
	"DILLINGHAM":           "DILLINGHAM",
	"DOUGLAS":              "JUNEAU",
	"DUTCH HARBOR":         "ALEUTIANS WEST",
	"EAGLE":                "SOUTHEAST FAIRBANKS",
	"EAGLE RIVER":          "ANCHORAGE",
	"EEK":                  "BETHEL",
	"EGEGIK":               "LAKE AND PENINSULA",
	"EIELSON AFB":          "FAIRBANKS NORTH STAR",
	"EKWOK":                "DILLINGHAM",
	"ELFIN COVE":           "HOONAH ANGOON",
	"ELIM":                 "NOME",
	"EMMONAK":              "WADE HAMPTON",
	"ESTER":                "FAIRBANKS NORTH STAR",
	"FAIRBANKS":            "FAIRBANKS NORTH STAR",
	"FALSE PASS":           "ALEUTIANS EAST",
	"FORT GREELY":          "SOUTHEAST FAIRBANKS",
	"FORT WAINWRIGHT":      "FAIRBANKS NORTH STAR",
	"FORT YUKON":           "YUKON KOYUKUK",
	"GAKONA":               "VALDEZ CORDOVA",
	"GALENA":               "YUKON KOYUKUK",
	"GAMBELL":              "NOME",
	"GIRDWOOD":             "ANCHORAGE",
	"GLENNALLEN":           "VALDEZ CORDOVA",
	"GOODNEWS BAY":         "BETHEL",
	"GRAYLING":             "YUKON KOYUKUK",
	"GUSTAVUS":             "HOONAH ANGOON",
	"HAINES":               "HAINES",
	"HEALY":                "DENALI",
	"HOLY CROSS":           "YUKON KOYUKUK",
	"HOMER":                "KENAI PENINSULA",
	"HOONAH":               "HOONAH ANGOON",
	"HOOPER BAY":           "WADE HAMPTON",
	"HOPE":                 "KENAI PENINSULA",
	"HOUSTON":              "MATANUSKA SUSITNA",
	"HUGHES":               "YUKON KOYUKUK",
	"HUSLIA":               "YUKON KOYUKUK",
	"HYDABURG":             "PRINCE OF WALES HYDER",
	"HYDER":                "PRINCE OF WALES HYDER",
	"ILIAMNA":              "LAKE AND PENINSULA",
	"INDIAN":               "ANCHORAGE",
	"JBER":                 "ANCHORAGE",
	"JUNEAU":               "JUNEAU",
	"KAKE":                 "PETERSBURG",
	"KAKTOVIK":             "NORTH SLOPE",
	"KALSKAG":              "BETHEL",
	"KALTAG":               "YUKON KOYUKUK",
	"KARLUK":               "KODIAK ISLAND",
	"KASIGLUK":             "BETHEL",
	"KASILOF":              "KENAI PENINSULA",
	"KENAI":                "KENAI PENINSULA",
	"KETCHIKAN":            "KETCHIKAN GATEWAY",
	"KIANA":                "NORTHWEST ARCTIC",
	"KING COVE":            "ALEUTIANS EAST",
	"KING SALMON":          "BRISTOL BAY",
	"KIPNUK":               "BETHEL",
	"KIVALINA":             "NORTHWEST ARCTIC",
	"KLAWOCK":              "PRINCE OF WALES HYDER",
	"KOBUK":                "NORTHWEST ARCTIC",
	"KODIAK":               "KODIAK ISLAND",
	"KONGIGANAK":           "BETHEL",
	"KOTLIK":               "WADE HAMPTON",
	"KOTZEBUE":             "NORTHWEST ARCTIC",
	"KOYUK":                "NOME",
	"KOYUKUK":              "YUKON KOYUKUK",
	"KWETHLUK":             "BETHEL",
	"KWIGILLINGOK":         "BETHEL",
	"LAKE MINCHUMINA":      "YUKON KOYUKUK",
	"LARSEN BAY":           "KODIAK ISLAND",
	"LEVELOCK":             "LAKE AND PENINSULA",
	"LOWER KALSKAG":        "BETHEL",
	"MANLEY HOT SPRINGS":   "YUKON KOYUKUK",
	"MANOKOTAK":            "DILLINGHAM",
	"MARSHALL":             "WADE HAMPTON",
	"MC GRATH":             "YUKON KOYUKUK",
	"MEKORYUK":             "BETHEL",
	"METLAKATLA":           "PRINCE OF WALES HYDER",
	"MEYERS CHUCK":         "KETCHIKAN GATEWAY",
	"MINTO":                "YUKON KOYUKUK",
	"MOOSE PASS":           "KENAI PENINSULA",
	"MOUNTAIN VILLAGE":     "WADE HAMPTON",
	"NAKNEK":               "BRISTOL BAY",
	"NAPAKIAK":             "BETHEL",
	"NENANA":               "YUKON KOYUKUK",
	"NEW STUYAHOK":         "DILLINGHAM",
	"NIGHTMUTE":            "BETHEL",
	"NIKISKI":              "KENAI PENINSULA",
	"NIKOLAI":              "YUKON KOYUKUK",
	"NIKOLSKI":             "ALEUTIANS WEST",
	"NINILCHIK":            "KENAI PENINSULA",
	"NOATAK":               "NORTHWEST ARCTIC",
	"NOME":                 "NOME",
	"NONDALTON":            "LAKE AND PENINSULA",
	"NOORVIK":              "NORTHWEST ARCTIC",
	"NORTH POLE":           "FAIRBANKS NORTH STAR",
	"NORTHWAY":             "SOUTHEAST FAIRBANKS",
	"NUIQSUT":              "NORTH SLOPE",
	"NULATO":               "YUKON KOYUKUK",
	"NUNAM IQUA":           "WADE HAMPTON",
	"NUNAPITCHUK":          "BETHEL",
	"OLD HARBOR":           "KODIAK ISLAND",
	"OUZINKIE":             "KODIAK ISLAND",
	"PALMER":               "MATANUSKA SUSITNA",
	"PEDRO BAY":            "LAKE AND PENINSULA",
	"PELICAN":              "HOONAH ANGOON",
	"PERRYVILLE":           "LAKE AND PENINSULA",
	"PETERSBURG":           "PETERSBURG",
	"PILOT POINT":          "LAKE AND PENINSULA",
	"PILOT STATION":        "WADE HAMPTON",
	"PLATINUM":             "BETHEL",
	"POINT BAKER":          "PRINCE OF WALES HYDER",
	"POINT HOPE":           "NORTH SLOPE",
	"POINT LAY":            "NORTH SLOPE",
	"PORT ALEXANDER":       "SITKA",
	"PORT ALSWORTH":        "LAKE AND PENINSULA",
	"PORT HEIDEN":          "LAKE AND PENINSULA",
	"PORT LIONS":           "KODIAK ISLAND",
	"PRUDHOE BAY":          "NORTH SLOPE",
	"QUINHAGAK":            "BETHEL",
	"RAMPART":              "YUKON KOYUKUK",
	"RED DEVIL":            "BETHEL",
	"RUBY":                 "YUKON KOYUKUK",
	"RUSSIAN MISSION":      "WADE HAMPTON",
	"SAINT GEORGE ISLAND":  "ALEUTIANS WEST",
	"SAINT MARYS":          "WADE HAMPTON",
	"SAINT MICHAEL":        "NOME",
	"SAINT PAUL ISLAND":    "ALEUTIANS WEST",
	"SALCHA":               "FAIRBANKS NORTH STAR",
	"SAND POINT":           "ALEUTIANS EAST",
	"SAVOONGA":             "NOME",
	"SCAMMON BAY":          "WADE HAMPTON",
	"SELAWIK":              "NORTHWEST ARCTIC",
	"SELDOVIA":             "KENAI PENINSULA",
	"SEWARD":               "KENAI PENINSULA",
	"SHAGELUK":             "YUKON KOYUKUK",
	"SHAKTOOLIK":           "NOME",
	"SHISHMAREF":           "NOME",
	"SHUNGNAK":             "NORTHWEST ARCTIC",
	"SITKA":                "SITKA",
	"SKAGWAY":              "SKAGWAY",
	"SKWENTNA":             "MATANUSKA SUSITNA",
	"SLEETMUTE":            "BETHEL",
	"SOLDOTNA":             "KENAI PENINSULA",
	"SOUTH NAKNEK":         "BRISTOL BAY",
	"STEBBINS":             "NOME",
	"STERLING":             "KENAI PENINSULA",
	"STEVENS VILLAGE":      "YUKON KOYUKUK",
	"SUTTON":               "MATANUSKA SUSITNA",
	"TAKOTNA":              "YUKON KOYUKUK",
	"TALKEETNA":            "MATANUSKA SUSITNA",
	"TANACROSS":            "SOUTHEAST FAIRBANKS",
	"TANANA":               "YUKON KOYUKUK",
	"TATITLEK":             "VALDEZ CORDOVA",
	"TELLER":               "NOME",
	"TENAKEE SPRINGS":      "HOONAH ANGOON",
	"THORNE BAY":           "PRINCE OF WALES HYDER",
	"TOGIAK":               "DILLINGHAM",
	"TOK":                  "SOUTHEAST FAIRBANKS",
	"TOKSOOK BAY":          "BETHEL",
	"TRAPPER CREEK":        "MATANUSKA SUSITNA",
	"TULUKSAK":             "BETHEL",
	"TUNTUTULIAK":          "BETHEL",
	"TUNUNAK":              "BETHEL",
	"TWO RIVERS":           "FAIRBANKS NORTH STAR",
	"TYONEK":               "KENAI PENINSULA",
	"UNALAKLEET":           "NOME",
	"UNALASKA":             "ALEUTIANS WEST",
	"VALDEZ":               "VALDEZ CORDOVA",
	"VENETIE":              "YUKON KOYUKUK",
	"WAINWRIGHT":           "NORTH SLOPE",
	"WALES":                "NOME",
	"WARD COVE":            "KETCHIKAN GATEWAY",
	"WASILLA":              "MATANUSKA SUSITNA",
	"WHITE MOUNTAIN":       "NOME",
	"WHITTIER":             "VALDEZ CORDOVA",
	"WILLOW":               "MATANUSKA SUSITNA",
	"WRANGELL":             "WRANGELL",
	"YAKUTAT":              "YAKUTAT",
}
